spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rtm
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 1000MB


file:
  upload:
    acceptableTextExtensions: txt


minio:
  url: http://127.0.0.1:9090/
  bucket: rtm
  access-key: minioadmin
  secret-key: minioadmin
  answers-folder: answers/
  results-folder: results/
